### PR TITLE
Limit length of choice's title to 256 characters

### LINKED ISSUE #273: dmlwriteexception if title too long
Creating a choice throws a dmlwriteexception if the title is too long. The title is defined as VARCHAR(255) in the database schema. If the user tries to use an amount of characters above that limit, a dmlwriteexception will be thrown which is pretty bad especially when debugging is turned off, because the user does not receive any feedback about what's wrong.

Solution: The frontend (mform) needs to validate the correct length of the title. If not, notify the user about it.

This also applies to csv import. Here as well a check is needed and the issue should be reported to the user using the already implemented way of alerting the user about errors while importing.

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #273

### CODE REVIEW

File: classes/choice_importer.php [hunk 1]
```diff
@@ -173,6 +173,13 @@ public function import($content, $live=true) {
                                 continue;
                             }
 
+                            if ($fieldname === 'title' && strlen($cell) > 255) {
+                                $importstatus->status = self::IMPORT_STATUS_DATA_ERROR;
+                                $importstatus->errors[] = get_string('csvupload_too_long_title',
+                                        RATINGALLOCATE_MOD_NAME, $cell);
+                                break;
```
Comment (Laur0r) [inline classes/choice_importer.php:180]: This break only exits the loop for mapping cell content to field names. This leads to creating choices which do not have a title if its too long. But a choice shouldn't be created in these cases. Hence, there should be some form of check whether an error is present when creating them in lines 211-214.

**Review by Laur0r — CHANGES_REQUESTED** [review]
Welcome back @PhMemmel :) 
Thanks for spotting this problem and providing a pull request for it! I have noticed some issues, it would be great if you could fix these.

File: classes/choice_importer.php (hunk 1 above)
Comment (PhMemmel) [reply classes/choice_importer.php:180]: Yes, good catch. I might have been a bit fast there, sorry.

I now changed the behavior so that other choices are being properly imported, only the one with the too long title is being skipped and an error is thrown. I am not sure, if this is ideal. Would you suggest to cancel the whole import?

File: lang/en/ratingallocate.php [hunk 2]
```diff
@@ -219,6 +219,7 @@
 $string['deleteconfirm'] = 'Do you really want to delete the choice "{$a}"?';
 $string['choice_deleted_notification'] = 'Choice "{$a}" was deleted.';
 $string['choice_deleted_notification_error'] = 'Choice requested for deletion could not be found.';
+$string['title_too_long_error'] = 'The title of the choice has too many characters, only 256 are allowed.';
```
[the remark this answers is not in the document]
Comment (PhMemmel) [reply lang/en/ratingallocate.php]: definitely :innocent:

File: classes/choice_importer.php (hunk 1 above)
Comment (Laur0r) [reply classes/choice_importer.php]: Thanks! I also thought about it, I think it's more intuitive if we keep it like this and already import the other choices. Although I noticed that you can import the same choice twice. It would make more sense if the title is unique, however I'm not sure whether there exists some corner scenarios for which teachers want to create separate choices with the same name. I'll create an issue for that.

Comment (Laur0r) [reply classes/choice_importer.php]: Yes that sounds like a nice feature, feel free to add an issue for that :)

**Review by Laur0r — APPROVED** [review]
Thanks, all looks good now!
